apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wizard-intelligence-network.fullname" $ }}
  annotations:
    kubernetes.io/ingress.class: traefik 
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "wizard-intelligence-network.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}