apiVersion: v1
kind: Service
metadata:
  name: {{ include "wizard-intelligence-network.fullname" . }}
  labels:
    {{- include "wizard-intelligence-network.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "wizard-intelligence-network.selectorLabels" . | nindent 4 }}
